name: Trigger Videodb Helper Update

on:
  pull_request:
    types: [closed]

jobs:
  trigger-repo1:
    if: ${{ github.event.pull_request.merged && github.event.pull_request.base.ref == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger VideoDB helper Update workflow via repository_dispatch
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer ${{ secrets.VIDEODB_HELPER_TOKEN}}" \
               -H "X-GitHub-Api-Version: 2022-11-28" \
               https://api.github.com/repos/videodb-db/videodb-helper/dispatches \
               -d '{"event_type": "sdk-pr-merged", "client_payload": {"pr_number": ${{ github.event.pull_request.number }}}}'